version: '3.8'
services:
  shellinabox:
    build:
      context: .
      dockerfile: shellinabox.Dockerfile
    ports:
     - "4200:4200"
    networks:
      - app-network
    volumes:
      - user_programs:/home/shelluser
  web:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
     - "5000:5000"
    networks:
     - app-network
  check:
    build:
      context: .
      dockerfile: check.Dockerfile
    ports:
      - "5172:5172"
    networks:
      - app-network
    volumes:
      - user_programs:/app/user_programs
volumes:
  user_programs:
    name: user_programs
networks:
  app-network:
    driver: bridge
