version: '3.8'
services:
  shellinabox:
    build:
      context: .
      dockerfile: shellinabox.Dockerfile
    ports:
     - "4200:4200"
    networks:
      - app-network
  web:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
     - "5000:5000"
    networks:
     - app-network
networks:
  app-network:
    driver: bridge
